name: Build and Test

on: [ pull_request ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew assembleDebug

      - name: Test
        run:  ./gradlew testDebugUnitTest

      - name: Generate Jacoco coverage reports
        run: ./gradlew jacocoTestReport

      - name: Sending Covergage Reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov \
          chmod +x codecov \
          ./codecov